[package]
name = "xyz-dlp"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
scraper = "0.13"
anyhow = "1.0"
thiserror = "1.0"
indicatif = "0.17"
